# Generated by Django 5.1.4 on 2025-04-20 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_alter_shippingaddress_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='customer',
            new_name='profile',
        ),
    ]
