# Generated by Django 5.1.4 on 2025-04-20 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_rename_customer_shippingaddress_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='profile',
            new_name='customer',
        ),
    ]
