# Generated by Django 5.1.4 on 2025-04-20 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_rename_profile_shippingaddress_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='customer',
        ),
    ]
