# Generated by Django 4.1.7 on 2023-05-05 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_shoppingcart_items_shoppingcart_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='total_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
