# Generated by Django 4.1.7 on 2023-05-06 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_shoppingcart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='cart_item_price',
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='cart_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.product'),
            preserve_default=False,
        ),
    ]
