# Generated by Django 4.1.7 on 2023-05-06 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_remove_shoppingcart_cart_item_price_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
    ]
