# Generated by Django 4.1.7 on 2023-05-06 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_shoppingcart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
    ]
