# Generated by Django 4.1.7 on 2023-05-10 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_customer_total_spent'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='cart_status',
            field=models.IntegerField(blank=True, default='1'),
        ),
    ]
