# Generated by Django 5.1.4 on 2024-12-17 17:09

import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_deliveryaddress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=30, prefix='order', unique=True)),
                ('total_amount', models.IntegerField(blank=True, null=True)),
                ('payment_method', models.CharField(default='PayPal', max_length=50)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('cart_items', models.ManyToManyField(to='base.shoppingcart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
